language:
- cpp

os:
- osx
- linux

compiler:
- clang

# check environment (copied from libgit2sharp)
before_install:
- date -u
- uname -a
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/linux_before_install.sh; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_before_install.sh; fi

# make sure cmake is installed, set up latest GCC C++ compiler if necessary
install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/linux_install.sh; fi
# - if [ "${TRAVIS_OS_NAME}" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_install.sh; fi

# TODO: could move script to separate file
script: mkdir build && cd build && cmake .. && make
